spring:
  application:
    name: weather-application
  datasource:
    url: jdbc:postgresql://db:5432/db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
weather:
  api:
    key: eeed6c1dbfbf4263db33803caee57275
